Website/Catalog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('search/', search_catalog, name='search_catalog'),
    path('view/item/', view_item, name='view_item'),
    path('choose/', choose_catalog, name='choose_catalog'),
    # ... other url patterns ...
]

Website/about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Path Converters
    # int: numbers
    # str: strings
    # path: whole urls /
    # slug: hyphen-and_underscores_stuff
    # UUID: universally unique identifer (usernames & such)

    path('', views.about_page, name="about_page"),
]

Website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('', include('members.urls')),
    path('catalog/', include('Catalog.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('application/', include ('application.urls')),
    path('report/', include('report.urls')),
]

Website/Catalog/models.py
from django.db import models

# Create your models here.

# class Product(models.Model):
#     image = models.ImageField(upload_to='product_images/', null=True, blank=True)
#     name = models.CharField(max_length=255,blank=True)
#     artist = models.CharField(max_length=255, blank=True)
#     genre = models.CharField(max_length=255, blank=True)
#     description = models.TextField(max_length=250, blank=True)
#     point_price = models.IntegerField(default=0)
#     # Add other fields as needed

Website/Catalog/forms.py
from django import forms
# from .models import Product

# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ['name', 'artist']

Website/members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, DriverProfile, SponsorUserProfile, SponsorList, PointReason


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'middle_initial', 'email']

class DriverProfileForm(UserProfileForm):
    class Meta:
        model = DriverProfile
        fields = ['first_name', 'middle_initial', 'last_name', 'phone_number', 'email', 'date_of_birth', 'street_address', 'city', 'state', 'zipcode', 'drivers_license', 'year', 'make', 'model', 'vin', 'provider_name', 'policy_number', 'emergency_contact_name', 'emergency_contact_phone']
    def __init__(self, *args, **kwargs):
        super(DriverProfileForm, self).__init__(*args, **kwargs)
        
        self.fields['first_name'].widget.attrs['class'] = 'form-control-sm'
        self.fields['middle_initial'].widget.attrs['class'] = 'form-control-sm'
        self.fields['last_name'].widget.attrs['class'] = 'form-control-sm'
        self.fields['phone_number'].widget.attrs['class'] = 'form-control-sm'
        self.fields['email'].widget.attrs['class'] = 'form-control-sm'
        self.fields['date_of_birth'].widget.attrs['class'] = 'form-control-sm'
        self.fields['street_address'].widget.attrs['class'] = 'form-control-sm'
        self.fields['city'].widget.attrs['class'] = 'form-control-sm'
        self.fields['state'].widget.attrs['class'] = 'form-control-sm'
        self.fields['zipcode'].widget.attrs['class'] = 'form-control-sm'
        self.fields['drivers_license'].widget.attrs['class'] = 'form-control-sm'
        self.fields['year'].widget.attrs['class'] = 'form-control-sm'
        self.fields['make'].widget.attrs['class'] = 'form-control-sm'
        self.fields['model'].widget.attrs['class'] = 'form-control-sm'
        self.fields['vin'].widget.attrs['class'] = 'form-control-sm'
        self.fields['provider_name'].widget.attrs['class'] = 'form-control-sm'
        self.fields['policy_number'].widget.attrs['class'] = 'form-control-sm'
        self.fields['emergency_contact_name'].widget.attrs['class'] = 'form-control-sm'
        self.fields['emergency_contact_phone'].widget.attrs['class'] = 'form-control-sm'

class AssignSponsorForm(forms.ModelForm):
    class Meta:
        model = SponsorUserProfile
        fields = ('sponsor_name',)
    
    sponsor_name = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super(AssignSponsorForm, self).__init__(*args, **kwargs)
        self.fields['sponsor_name'].choices = self.get_choices()

    def get_choices(self):
        choices = SponsorList.objects.values_list('sponsor_name', 'sponsor_name').distinct()
        return choices
    
class ChooseSponsorForm(forms.Form):
    sponsor_choices = forms.ChoiceField(label='Select Sponsor')

    def __init__(self, *args, **kwargs):
        sponsor_queryset = kwargs.pop('sponsor_queryset', None)
        super(ChooseSponsorForm, self).__init__(*args, **kwargs)
        
        if sponsor_queryset:
            sponsor_choices = [(sponsor.id, sponsor.sponsor_name) for sponsor in sponsor_queryset]
            self.fields['sponsor_choices'].choices = [('', '--- Select Sponsor ---')] + sponsor_choices
    
class PointReasonForm(forms.ModelForm):

    class Meta:
        model = PointReason
        fields = ['point_amt', 'is_add', 'point_reason',]

    def __init__(self, *args, **kwargs):
        super(PointReasonForm, self).__init__(*args, **kwargs)

        self.fields['point_amt'].widget.attrs['class'] = 'form-control'
        self.fields['is_add'].widget = forms.HiddenInput()
        self.fields['point_reason'].widget.attrs['class'] = 'form-control'

class EmailForm(forms.Form):
    email = forms.EmailField(label='Enter your email', max_length=75)

Website/Catalog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from urllib.parse import unquote
import requests
from django.contrib import messages
from members.forms import ChooseSponsorForm
from members.models import UserProfile, SponsorList, SponsorUserProfile

def choose_catalog(request):
    user_sponsors = SponsorList.objects.filter(sponsored_users__user=request.user)

    if request.method == "POST":
        form = ChooseSponsorForm(request.POST, sponsor_queryset=user_sponsors)
        if form.is_valid():
            selected_sponsor_id = form.cleaned_data['sponsor_choices']
            selected_sponsor = SponsorList.objects.get(id=selected_sponsor_id)
            
            # Perform actions with the selected sponsor, for example, store it in the session
            request.session['selected_sponsor'] = selected_sponsor.sponsor_name
            return redirect('search_catalog')
    else:
        form = ChooseSponsorForm(sponsor_queryset=user_sponsors)

    context = {
        'form': form,
    }
    return render(request, 'choose_catalog.html', context)

def search_catalog(request):
    if not request.user.is_authenticated:
        messages.error(request, "You need to log in or register to view this page.")
        return redirect('/')
    try:
        profile, created = UserProfile.objects.get_or_create(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None
    if not request.user.is_superuser and not profile.is_sponsor and not profile.is_driver:
        messages.error(request, "There is an error with your account, please contact Team06 at team06.onlydrivers@gmail.com for support.")
        return redirect('/about')

    request.session['last_search_url'] = request.get_full_path()
    search_type = 'itunes'

    if search_type == 'itunes':
        search_query = request.GET.get('search', '')
        country = request.GET.get('country', 'us')
        limit = request.GET.get('limit', '100')
        lang = request.GET.get('lang', 'en')
        explicit = request.GET.get('explicit', 'No')
        
        params = {
            'term': search_query,
            'media': 'all',
            'country': country,
            'limit': limit,
            'lang': lang,
            'explicit': explicit,
        }
        if profile.is_driver:
            sponsor_name = request.session.get('selected_sponsor')
            sponsor = SponsorList.objects.get(sponsor_name=sponsor_name)
        elif profile.is_sponsor:
            sponsor_user = SponsorUserProfile.objects.get(user=request.user)
            sponsor = SponsorList.objects.get(sponsor_name=sponsor_user.sponsor_name)
        
        response = requests.get('https://itunes.apple.com/search', params=params)
        if response.status_code == 200:
            itunes_data = response.json()
            products = []
            matched_artist_results = []
            other_results = []

            for item in itunes_data.get('results', []):
                title = item.get('trackName')
                artist = item.get('artistName')
                image_url = item.get('artworkUrl100')
                new_url = image_url.replace('100x100bb.jpg', '600x600bb.jpg')
                    
                track_price = item.get('trackPrice', 0)
                if profile.is_driver:
                    point_conversion = sponsor.point_conversion
                    track_price = int(track_price / point_conversion)

                # Check if the title is 'The Hunger Games' to override the details
                if title == "The Hunger Games":
                    artist = "Gary Lu"  # Corrected artist name
                    genre = "Action"
                    track_price = 7.99  # Updated price
                    if profile.is_driver:
                        track_price = int(track_price / point_conversion)

                product = {
                    'title': title,
                    'artist': artist,
                    'image': new_url,
                    'genre': item.get('primaryGenreName'),
                    'price': track_price
                }

                # Prioritize results where the artist's name matches the search query
                if search_query.lower() in artist.lower():
                    matched_artist_results.append(product)
                else:
                    other_results.append(product)

            # Combine the matched artist results and other results
            sorted_products = matched_artist_results + other_results

            for product in sorted_products:
                if product['price'] > 0:
                    products.append(product)

            if profile.is_driver or profile.is_sponsor:
                context = {
                    'products': products,
                    'profile': profile,
                    'term': search_query,
                    'sponsor': sponsor,
                }
            elif request.user.is_superuser:
                context = {
                    'products': products,
                    'profile': profile,
                    'term': search_query,
                }
            response = render(request, 'product_list.html', context)
            response['Cache-Control'] = 'no-cache, no-store, must-revalidate'
            response['Pragma'] = 'no-cache'
            response['Expires'] = '0'
            return response

        else:
            context = {'error': 'An error occurred while fetching data from iTunes.'}
            return render(request, 'error.html', context)

    else:
        return HttpResponse("Unsupported search type", status=400)
    
def view_item(request):
    if not request.user.is_authenticated:
        messages.error(request, "You need to log in or register to view this page.")
        return redirect('/')
    try:
        profile, created = UserProfile.objects.get_or_create(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None
    if not request.user.is_superuser and not profile.is_sponsor and not profile.is_driver:
        messages.error(request, "There is an error with your account, please contact Team06 at team06.onlydrivers@gmail.com for support.")
        return redirect('/about')
    
    title = unquote(request.GET.get('title', ''))
    artist = unquote(request.GET.get('artist', ''))
    image = unquote(request.GET.get('image', ''))
    genre = unquote(request.GET.get('genre', ''))
    price = unquote(request.GET.get('price', ''))
    last_search_url = request.session.get('last_search_url')

    resized_image = image.replace('600x600bb.jpg', '450x450bb.jpg')

    context = {
        'title': title,
        'artist': artist,
        'image': resized_image,
        'genre': genre,
        'price': price,
        'profile': profile,
        'last_search_url': last_search_url,
        # Any additional data you want to send to the template
    }
    return render(request, 'view_item.html', context)

Website/Catalog/templates/choose_catalog.html
{% extends "about/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <h1 class="text-center mb-4">Choose Catalog</h1>
            <form method="post" class="border rounded p-4 bg-light">
                {% csrf_token %}
                <p></p>
                <div class="form-group">
                    <label for="id_sponsor_choices">Select Sponsor:</label>
                    {{ form.sponsor_choices|add_class:"form-control" }}
                </div>
                <p></p>
                <p></p>
                <div class="text-center">
                    <button type="submit" class="btn btn-secondary">Select Sponsor</button>
                </div>
                <p></p>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Website/Catalog/templates/error.html
{% extends "about/base.html" %}

{% block content %}
<div class="shadow w-50 p-4 mx-auto bg-body rounded">
    <h1>Error</h1>
    <p>An error occurred:</p>
    <p>{{ error }}</p>
</div>
{% endblock content %}

Website/Catalog/templates/product_list.html
{% extends "about/base.html" %}

{% block content %}
<div class="p-2 bg-body rounded">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-8">
                {% if profile.is_driver %}
                    <h1 class="mb-4 text-center">{{ sponsor.sponsor_name }}'s Driver Catalog</h1>
                {% elif profile.is_sponsor %}
                    <h1 class="mb-4 text-center">{{ sponsor.sponsor_name }}'s Catalog</h1>
                {% elif user.is_superuser %}
                    <h1 class="mb-4 text-center">OnlyDrivers Catalog</h1>
                {% endif %}    
                <form action="{% url 'search_catalog' %}" method="GET">
                    <div class="input-group">
                        <input type="text" name="search" class="form-control" placeholder="Search...">
                        <button type="submit" class="btn btn-secondary">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="content" class="container mt-5">
    {% if products %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for product in products %}
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ product.image }}" class="card-img-top" alt="{{ product.title }} cover">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.title }}</h5>
                            <p class="card-text">Artist: {{ product.artist }}</p>
                            <p class="card-text">Genre: {{ product.genre }}</p>
                            <p class="card-text">
                                {% if profile.is_driver %}
                                    Points: {{ product.price }}
                                {% else %}
                                    Points: ${{ product.price }}
                                {% endif %}
                            </p>
                            <a href="{% url 'view_item' %}?title={{ product.title|urlencode }}&artist={{ product.artist|urlencode }}&image={{ product.image|urlencode }}&genre={{ product.genre|urlencode }}&price={{ product.price }}" class="btn btn-secondary">View Item</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% elif term == '' %}
        <p class="text-center text-danger fw-bold">Please enter a search term.</p>
    {% else %}
        <p>No products found.</p>
    {% endif %}

    {% if error %}
        <p>{{ error }}</p>
    {% endif %}
</div>

{% endblock %}

Website/Catalog/templates/view_item.html
{% extends "about/base.html" %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="shadow p-4 bg-body rounded text-center">
                <img src="{{ image }}" alt="{{ title }} cover" class="img-fluid mb-3">
                <h4>Title: {{ title }}</h4>
                <p>Artist: {{ artist }}</p>
                <p>Genre: {{ genre }}</p>
                {% if profile.is_driver %}
                    <p>Points: {{ price }}</p>
                {% else %}
                    <p>Points: ${{ price }}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<p></p>
<div class="row justify-content-start mt-3 col-md-6 mx-auto"><a href="{{ last_search_url }}" class="btn btn-outline-primary">Go Back</a></div>
<p></p>
{% endblock %}